#pragma once
#ifndef NYAA_RESOURCE_TEXT_IDS_INL_H_
#define NYAA_RESOURCE_TEXT_IDS_INL_H_

namespace nyaa {
namespace res {

#define DEFINE_TEXT_KINDS(V) \
    V(TEST_STRING_1) \
    V(TEST_STRING_2) \
    V(TITLE_OPTION_1) \
    V(TITLE_OPTION_2) \
    V(TITLE_OPTION_3) \
    V(TITLE_ROLE_1) \
    V(TITLE_ROLE_2) \
    V(TITLE_ROLE_3) \
    V(TITLE_ROLE_4) \
    V(TITLE_ROLE_5) \
    V(TITLE_MENU_NEW_WORLD) \
    V(TITLE_MENU_LOAD_WORLD) \
    V(TITLE_MENU_TEST_SCENE) \
    V(TITLE_MENU_EXIT) \
    V(CUBE_AIR) \
    V(CUBE_WALL_1) \
    V(CUBE_WOOD_1) \
    V(NICK_ONE_LINE_MAN) \
    V(ACTOR_JACK_LI) \
    V(ACTOR_NIKO_CHEN) \
    V(ACTOR_STEVE_WANG) \
    V(ACTOR_TOMMY_ZHANG) \
    V(ACTOR_TIMMY_ZHANG) \
    V(BASIC_SWORD_SKILL) \
    V(MIDDLE_SWORD_SKILL) \
    V(ADVANCE_SWORD_SKILL) \
    V(MASTER_SWORD_SKILL) \
    V(BASIC_LANCE_SKILL) \
    V(MIDDLE_LANCE_SKILL) \
    V(ADVANCE_LANCE_SKILL) \
    V(MASTER_LANCE_SKILL) \
    V(BASIC_SHOOTING_SKILL) \
    V(MIDDLE_SHOOTING_SKILL) \
    V(ADVANCE_SHOOTING_SKILL) \
    V(MASTER_SHOOTING_SKILL) \
    V(MASTER_ATTACK_ZERO) \


enum TextID {
#define DEFINE_ENUM(name) name,
    DEFINE_TEXT_KINDS(DEFINE_ENUM)
#undef DEFINE_ENUM
    MAX_TEXT_ID,
};  // enum TextID

} // namespace res
} // namespace nyaa

#endif // NYAA_RESOURCE_TEXT_IDS_INL_H_
